name: native-262k
max_model_len: 262144
rope: null
kv_cache_dtype: bfloat16
gpu_memory_utilization: 0.90
max_num_seqs: 4
max_num_batched_tokens: 8192
chunked_prefill_size: 8192
chunked_prefill: true
enable_prefix_caching: true
language_model_only: true
aiter: true
mtp: false
max_cudagraph_capture_size: 256
