name: yarn-1m
max_model_len: 1010000
rope:
  rope_type: yarn
  factor: 4.0
  original_max_position_embeddings: 262144
  mrope_interleaved: true
  mrope_section: [11, 11, 10]
  rope_theta: 10000000
  partial_rotary_factor: 0.25
kv_cache_dtype: bfloat16
gpu_memory_utilization: 0.90
max_num_seqs: 1
max_num_batched_tokens: 8192
chunked_prefill_size: 8192
chunked_prefill: true
enable_prefix_caching: true
language_model_only: true
aiter: true
mtp: false
max_cudagraph_capture_size: 128
